{
 "title": "⭐️ Обзор инфры (windows+linux)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_exporter", "label": "node_exporter", "query": { "query": "label_values(up, job)" } },
   {
    "name": "linux_hdd_exception",
    "label": "linux_hdd_exception",
    "query": {
     "query": "label_values(up{job=\"$node_exporter\"},instance)"
    }
   },
   { "name": "linux_redirect_uid", "label": "linux_redirect_uid", "query": "shumilov-full-node_exporter" },
   { "name": "back_uid", "label": "back_uid", "query": "shumilov-infra-table" },
   { "name": "windows_exporter", "label": "windows_exporter", "query": { "query": "label_values(up, job)" } },
   {
    "name": "windows_hdd_exception",
    "label": "windows_hdd_exception",
    "query": {
     "query": "label_values(up{job=\"$windows_exporter\"},instance)"
    }
   },
   { "name": "windows_redirect_uid", "label": "windows_redirect_uid", "query": "shumilov-full-windows_exporter" },
   { "name": "Filters" },
   { "name": "blackbox", "label": "blackbox", "query": { "query": "label_values(up, job)" } },
   { "name": "blackbox_redirect_uid", "label": "blackbox_uid", "query": "shumilov-full-blackbox" }
  ]
 },
 "panels": [
  {
   "title": "Linux",
   "type": "table",
   "description": "- Сортировка по колонкам\n\n- hdd_exception - список исключений для Disk stat - принудительный good\n\n- hdd_exception (All) = no exception",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"$node_exporter\"}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"$node_exporter\", mode=\"idle\"}[5m])) * 100)"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"$node_exporter\"} / node_memory_MemTotal_bytes{job=\"$node_exporter\"}))"
    },
    {
     "expr": "round(\n100 -\n(\nnode_filesystem_avail_bytes{\n    job=\"$node_exporter\",\n    fstype!~\"tmpfs|fuse.*|squashfs|iso9660|parsecfs|overlay|nsfs|proc|sysfs|cgroup.*\",\n    mountpoint!~\"/boot.*|/snap.*|/proc.*|/sys.*|/run.*\"\n}\n/\nnode_filesystem_size_bytes{\n    job=\"$node_exporter\",\n    fstype!~\"tmpfs|fuse.*|squashfs|iso9660|parsecfs|overlay|nsfs|proc|sysfs|cgroup.*\",\n    mountpoint!~\"/boot.*|/snap.*|/proc.*|/sys.*|/run.*\"\n}\n*100\n)\n)"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_read_bytes_total{job=\"$node_exporter\"}[5m]) + rate(node_disk_written_bytes_total{job=\"$node_exporter\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_reads_completed_total{job=\"$node_exporter\"}[5m]) + rate(node_disk_writes_completed_total{job=\"$node_exporter\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{job=\"$node_exporter\", device!~\"lo\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{job=\"$node_exporter\", device!~\"lo\"}[5m]))"
    },
    {
     "expr": "(node_boot_time_seconds{job=\"$node_exporter\", instance=~\"^($linux_hdd_exception)$\"} * 0 + 50) or max by (instance) (round(100 - (node_filesystem_avail_bytes{job=\"$node_exporter\", fstype!~\"tmpfs|fuse.*|squashfs|iso9660\", mountpoint!~\"/boot.*|/snap.*\", instance!~\"^($linux_hdd_exception)$\"} / node_filesystem_size_bytes{job=\"$node_exporter\", fstype!~\"tmpfs|fuse.*|squashfs|iso9660\", mountpoint!~\"/boot.*|/snap.*\", instance!~\"^(linux_$hdd_exception)$\"} * 100)))"
    }
   ]
  },
  {
   "title": "Blackbox",
   "type": "table",
   "description": "Blackbox Exporter monitoring overview\n\nShows:\n- URL being monitored\n- Probe status (UP/DOWN)\n- SSL certificate expiry (days remaining)\n\nColor coding:\n- Green: SSL expires in >1 day\n- Yellow: SSL expires in <1 day\n- Red: SSL expired or no SSL",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"$blackbox\"}"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"$blackbox\"} - time()) / 86400"
    },
    {
     "expr": "probe_http_status_code{job=\"$blackbox\"}"
    },
    {
     "expr": "probe_duration_seconds{job=\"$blackbox\"}"
    },
    {
     "expr": "probe_success{job=\"$blackbox\"} * 0 + 1"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "table",
   "description": "- Сортировка по колонкам\n\n- disk_exception - list of instances to force Disk stat to 'good'\n\n- disk_exception (All) = no exception\n\n- Compatible with Windows Exporter 0.29.2 and 0.31.3",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "time() - (\r\n  windows_system_boot_time_timestamp{job=\"$windows_exporter\"}\r\n    or windows_system_system_up_time{job=\"$windows_exporter\"}\r\n)"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=\"$windows_exporter\", mode=\"idle\"}[$__rate_interval])) * 100)"
    },
    {
     "expr": "100 * (1 - (\r\n  (windows_memory_available_bytes{job=\"$windows_exporter\"}\r\n    or windows_os_physical_memory_free_bytes{job=\"$windows_exporter\"})\r\n /\r\n  (windows_memory_physical_total_bytes{job=\"$windows_exporter\"}\r\n    or windows_cs_physical_memory_bytes{job=\"$windows_exporter\"})\r\n))"
    },
    {
     "expr": "round(\r\n  100 - 100 *\r\n  (\r\n    windows_logical_disk_free_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}\r\n      or windows_disk_free_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}\r\n  )\r\n  /\r\n  (\r\n    windows_logical_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}\r\n      or windows_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}\r\n  )\r\n)"
    },
    {
     "expr": "sum by (instance) (\r\n  (\r\n    rate(windows_logical_disk_read_bytes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n      or rate(windows_disk_read_bytes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n  )\r\n  +\r\n  (\r\n    rate(windows_logical_disk_write_bytes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n      or rate(windows_disk_write_bytes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n  )\r\n)"
    },
    {
     "expr": "sum by (instance) (\r\n  rate(windows_logical_disk_reads_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval]) +\r\n  rate(windows_logical_disk_writes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n)\r\nor\r\nsum by (instance) (\r\n  rate(windows_disk_reads_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval]) +\r\n  rate(windows_disk_writes_total{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\"}[$__rate_interval])\r\n)"
    },
    {
     "expr": "sum by (instance) (\r\n  rate(windows_net_bytes_received_total{job=\"$windows_exporter\", nic!~\"isatap.*|Pseudo.*\"}[$__rate_interval])\r\n  or\r\n  rate(windows_network_bytes_received_total{job=\"$windows_exporter\", nic!~\"isatap.*|Pseudo.*\"}[$__rate_interval])\r\n)"
    },
    {
     "expr": "sum by (instance) (rate(windows_net_bytes_sent_total{job=\"$windows_exporter\", nic!~\"isatap.*|Pseudo.*\"}[$__rate_interval]) or rate(windows_network_bytes_sent_total{job=\"$windows_exporter\", nic!~\"isatap.*|Pseudo.*\"}[$__rate_interval]))"
    },
    {
     "expr": "(\r\n  max by (instance) (\r\n    windows_logical_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance=~\"^($windows_hdd_exception)$\"}\r\n      or windows_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance=~\"^($windows_hdd_exception)$\"}\r\n  ) * 0 + 50\r\n)\r\nor\r\nmax by (instance) (\r\n  round(\r\n    100 - (\r\n      (windows_logical_disk_free_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance!~\"^($windows_hdd_exception)$\"}\r\n        or windows_disk_free_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance!~\"^($windows_hdd_exception)$\"})\r\n      /\r\n      (windows_logical_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance!~\"^($windows_hdd_exception)$\"}\r\n        or windows_disk_size_bytes{job=\"$windows_exporter\", volume!~\"HarddiskVolume.*\", instance!~\"^($windows_hdd_exception)$\"})\r\n      * 100\r\n    )\r\n  )\r\n)"
    }
   ]
  }
 ]
}